### ISSUE TITLE
May need to re-add prettier for non-js files

### ISSUE THREAD

**Issue by timja** [timja/github-comment-ops#57]
however this only applies to js files 😅

So potentially you want it for other files

_Originally posted by @jetersen in https://github.com/timja/github-comment-ops/pull/55#discussion_r928694204_

**Comment by jetersen** [comment]
instead of pre-commit, you could use lint-staged.
Which allows for multiple tools to run, see my use case here:

I use [`husky`](https://github.com/release-drafter/release-drafter/blob/master/.husky/pre-commit) to trigger [`lint-staged`](https://github.com/release-drafter/release-drafter/blob/master/lint-staged.config.js)

**Comment by timja** [comment]
> instead of pre-commit, you could use lint-staged. Which solves the same problem for linters, see my use case here:
> 
> I use [`husky`](https://github.com/release-drafter/release-drafter/blob/master/.husky/pre-commit?rgh-link-date=2022-07-25T10%3A25%3A06Z) to trigger [`lint-staged`](https://github.com/release-drafter/release-drafter/blob/master/lint-staged.config.js?rgh-link-date=2022-07-25T10%3A25%3A06Z)

I used that previously but I also wanted `helm-docs` ran as part of the lint.

If `lint-staged` can be made to work with that as well then that's fine.

https://github.com/timja/github-comment-ops/blob/main/.pre-commit-config.yaml#L2-L5

**Comment by timja** [comment]
Fixed in https://github.com/timja/github-comment-ops/pull/60
