### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by timja** [timja/github-comment-ops#7]

**Comment by jetersen** [comment]
Some suggestion for pure javascript

Hook up eslint and prettier and unicorn. Unicorn has sane defaults for modern javascript.
See my PR here https://github.com/updatecli/updatecli-action/pull/100

Add `jsconfig.json` should help with improve type detection for vscode.
Add `jsconfig.json` in your test folder that helps with jest type annotations.

`index.js` should really only be routing probot.

Everything else should be imported. FYI probot blocks you from switching to ESM. So stick with commonjs due to: https://github.com/probot/pino/pull/188
Because of it you need to turn off some features of unicorn, see [release-drafter eslintrc](https://github.com/release-drafter/release-drafter/blob/f4824e6ad8f4ac1e687db104bc43dfef0febaba7/.eslintrc#L13)

**Comment by timja** [comment]
Sure can have a look at unicorn.

Prettier is already in place here.

The typings already seem to work quite well but can add if it helps more.

and yeah will do eslint.

I have the start of some jest tests locally but didn't get much time yesterday on it.

----

Thanks for the suggestions

**Comment by timja** [comment]
> Link to unicorn eslint plugin at least: [sindresorhus/eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn)

:) I found it in your PR, but that would've helped, it didn't come up on google

**Comment by jetersen** [comment]
Great stuff 👏
